language: ruby
rvm:
  - 1.9.3
  - 2.0.0
script: 
- RAILS_ENV=test bundle exec rake --trace db:schema:load
- bundle exec rspec spec
matrix:
  allow_failures:
    - rvm: 2.0.0
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql